version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'Logging into Amazon ECR ...'
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 636578990471.dkr.ecr.eu-west-2.amazonaws.com
  build:
    on-failure: ABORT
    commands:
      - docker build -t $IMAGE .
      - docker tag $IMAGE:$IMAGE_TAG $REPOSITORY/$IMAGE:$IMAGE_TAG
  post_build:
    on-failure: ABORT
    commands:
      - docker images ls -a
      - docker push $REPOSITORY/$IMAGE:$IMAGE_TAG
